image_width: 1280
image_height: 1024
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1270.86826,    0.     ,  661.39526,
          0.     , 1271.21455,  516.79757,
          0.     ,    0.     ,    1. ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -0.209638, 0.138240, 0.000671, -0.000047, 0.000000 ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1., 0., 0.,
          0., 1., 0.,
          0., 0., 1. ]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1209.02002,    0.     ,  662.62243,    0.     ,
          0.     , 1229.0332 ,  517.05773,    0.     ,
          0.     ,    0.     ,    1.     ,    0. ]
